import express from 'express';
import cors from 'cors';
import { z } from 'zod';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import { spawnSync } from 'node:child_process';
import multer from 'multer';
import { db } from './db.js';
import { matchProduct, readOrderFile } from './order-reader.js';

const app = express();
app.use(cors()); app.use(express.json());
app.use('/uploads', express.static(fileURLToPath(new URL('../uploads', import.meta.url))));
const orderUpload=multer({storage:multer.memoryStorage(),limits:{files:30,fileSize:20*1024*1024}});

const movementMap = {
  FACTORY_IN: { from: null, to: 'FACTORY' }, FACTORY_OUT: { from: 'FACTORY', to: null },
  PICKING_IN: { from: 'FACTORY', to: 'PICKING' }, PICKING_OUT: { from: 'PICKING', to: null },
  PICKING_RETURN: { from: 'PICKING', to: 'FACTORY' }
} as const;

app.get('/api/health', (_req,res) => res.json({ ok: true }));
app.get('/api/vendors',(_req,res)=>res.json(db.prepare('SELECT id,name,memo,created_at FROM vendors WHERE active=1 ORDER BY name COLLATE NOCASE').all()));
app.post('/api/vendors',(req,res,next)=>{try{const data=z.object({name:z.string().trim().min(1,'거래처명을 입력해 주세요.'),memo:z.string().trim().default('')}).parse(req.body);const existing=db.prepare('SELECT id FROM vendors WHERE name=?').get(data.name) as {id:number}|undefined;if(existing){db.prepare('UPDATE vendors SET memo=?,active=1 WHERE id=?').run(data.memo,existing.id);return res.status(200).json({id:existing.id,...data})}const result=db.prepare('INSERT INTO vendors(name,memo) VALUES(?,?)').run(data.name,data.memo);res.status(201).json({id:Number(result.lastInsertRowid),...data})}catch(error){next(error)}});
app.patch('/api/vendors/:id',(req,res,next)=>{try{const data=z.object({name:z.string().trim().min(1),memo:z.string().trim().default('')}).parse(req.body);db.prepare('UPDATE vendors SET name=?,memo=? WHERE id=? AND active=1').run(data.name,data.memo,req.params.id);res.json({ok:true})}catch(error){next(error)}});
app.delete('/api/vendors/:id',(req,res,next)=>{try{db.prepare('UPDATE vendors SET active=0 WHERE id=?').run(req.params.id);res.json({ok:true})}catch(error){next(error)}});
app.get('/api/products', (_req,res) => res.json(db.prepare(`SELECT p.*, COALESCE(f.quantity,0) factoryStock, COALESCE(k.quantity,0) pickingStock, COALESCE(f.quantity,0)+COALESCE(k.quantity,0) totalStock FROM products p LEFT JOIN inventory f ON f.product_id=p.id AND f.location='FACTORY' LEFT JOIN inventory k ON k.product_id=p.id AND k.location='PICKING' WHERE p.active=1 ORDER BY p.id DESC`).all()));
app.get('/api/products/barcode/:barcode', (req,res) => { const product=db.prepare(`SELECT p.*, COALESCE(f.quantity,0) factoryStock, COALESCE(k.quantity,0) pickingStock FROM products p LEFT JOIN inventory f ON f.product_id=p.id AND f.location='FACTORY' LEFT JOIN inventory k ON k.product_id=p.id AND k.location='PICKING' WHERE p.barcode=? AND p.active=1`).get(req.params.barcode); if(!product) return res.status(404).json({message:'등록되지 않은 바코드입니다.'}); res.json(product); });
app.post('/api/products', (req,res,next) => { try { const d=z.object({sku:z.string().min(1),name:z.string().min(1),color:z.string().default(''),barcode:z.string().trim().optional()}).parse(req.body); const result=db.transaction(()=>{const r=db.prepare('INSERT INTO products(sku,name,color,barcode) VALUES(?,?,?,?)').run(d.sku,d.name,d.color,d.barcode||null); db.prepare("INSERT INTO inventory VALUES (?, 'FACTORY', 0), (?, 'PICKING', 0)").run(r.lastInsertRowid,r.lastInsertRowid); return r;})(); res.status(201).json({id:Number(result.lastInsertRowid),...d}); } catch(e){next(e)} });
app.get('/api/inventory', (_req,res) => res.json(db.prepare(`SELECT p.id,p.sku,p.name,p.color,p.barcode,p.image_path,p.catalog_name,COALESCE(f.quantity,0) factoryStock,COALESCE(k.quantity,0) pickingStock,COALESCE(f.quantity,0)+COALESCE(k.quantity,0) totalStock FROM products p LEFT JOIN inventory f ON f.product_id=p.id AND f.location='FACTORY' LEFT JOIN inventory k ON k.product_id=p.id AND k.location='PICKING' WHERE p.active=1 ORDER BY p.name,p.color`).all()));
app.get('/api/dashboard-inventory', (_req,res) => { const allRows=db.prepare(`SELECT p.id,p.name,p.image_path,p.catalog_name,COALESCE(f.quantity,0) factoryStock,COALESCE(k.quantity,0) pickingStock,COALESCE(f.quantity,0)+COALESCE(k.quantity,0) totalStock FROM products p LEFT JOIN inventory f ON f.product_id=p.id AND f.location='FACTORY' LEFT JOIN inventory k ON k.product_id=p.id AND k.location='PICKING' WHERE p.active=1`).all() as Array<Record<string,unknown>>; const names=JSON.parse(fs.readFileSync(fileURLToPath(new URL('../data/inventory-names.json',import.meta.url)),'utf8')) as string[]; const nameSet=new Set(names); const rows=allRows.filter(row=>nameSet.has(String(row.catalog_name||row.name))); const present=new Set(rows.map(row=>String(row.catalog_name||row.name))); let virtualId=-1; for(const name of names){if(!present.has(name))rows.push({id:virtualId--,name,catalog_name:name,image_path:null,factoryStock:0,pickingStock:0,totalStock:0})} res.json(rows); });
app.get('/api/movements', (req,res) => res.json(db.prepare(`SELECT m.*,p.sku,p.name,p.color FROM movements m JOIN products p ON p.id=m.product_id ORDER BY m.id DESC LIMIT ?`).all(Math.min(Number(req.query.limit)||100,500))));
app.get('/api/labels', (req,res) => { const search=`%${String(req.query.search||'')}%`; const vendor=String(req.query.vendor||''); res.json(db.prepare(`SELECT l.id,l.vendor,l.category,l.product_name,l.barcode,l.template_data,l.product_id,p.image_path FROM label_templates l LEFT JOIN products p ON p.id=l.product_id WHERE (?='' OR l.vendor=?) AND (l.product_name LIKE ? OR l.barcode LIKE ?) ORDER BY l.vendor,l.category,l.product_name LIMIT 5000`).all(vendor,vendor,search,search)); });
app.get('/api/labels/vendors', (_req,res) => res.json(db.prepare('SELECT vendor,COUNT(*) count FROM label_templates GROUP BY vendor ORDER BY vendor').all()));
app.post('/api/order-imports',orderUpload.array('files',30),async(req,res,next)=>{try{
  const vendor=z.string().trim().min(1,'거래처를 선택해 주세요.').parse(req.body.vendor);if(!db.prepare('SELECT id FROM vendors WHERE name=? AND active=1').get(vendor))throw new Error('등록된 거래처를 선택해 주세요.');const files=(req.files||[]) as Express.Multer.File[];if(!files.length)throw new Error('주문서 파일을 선택해 주세요.');
  const products=db.prepare('SELECT id,name,catalog_name,sku FROM products WHERE active=1').all() as Array<{id:number;name:string;catalog_name:string|null;sku:string}>;
  const insertImport=db.prepare('INSERT INTO order_imports(vendor,filename,file_type,status,raw_text) VALUES(?,?,?,?,?)');const insertItem=db.prepare('INSERT INTO order_import_items(import_id,source_name,quantity,matched_product_id,confidence) VALUES(?,?,?,?,?)');const updateStatus=db.prepare('UPDATE order_imports SET status=? WHERE id=?');const imports=[];
  for(const file of files){const parsed=await readOrderFile(file);const result=insertImport.run(vendor,file.originalname,file.mimetype,'REVIEW',parsed.raw.slice(0,100000));const importId=Number(result.lastInsertRowid);let unmatched=0;for(const row of parsed.rows){const match=matchProduct(row.name,products);if(!match)unmatched++;insertItem.run(importId,row.name,row.quantity,match?.id||null,match?.score||0)}const status=parsed.rows.length&&unmatched===0?'READY':'REVIEW';updateStatus.run(status,importId);imports.push({id:importId,filename:file.originalname,rows:parsed.rows.length,unmatched,status})}
  res.status(201).json({imports});
}catch(error){next(error)}});
app.get('/api/order-imports',(_req,res)=>{
  const imports=db.prepare(`SELECT o.*,COUNT(i.id) item_count,COALESCE(SUM(i.quantity),0) total_quantity,SUM(CASE WHEN i.matched_product_id IS NULL THEN 1 ELSE 0 END) unmatched_count FROM order_imports o LEFT JOIN order_import_items i ON i.import_id=o.id GROUP BY o.id ORDER BY o.id DESC`).all();
  const items=db.prepare(`SELECT i.*,o.vendor,o.filename,p.name matched_name,p.sku FROM order_import_items i JOIN order_imports o ON o.id=i.import_id LEFT JOIN products p ON p.id=i.matched_product_id WHERE o.status!='COMMITTED' ORDER BY o.id DESC,i.id`).all();
  const summary=db.prepare(`
    WITH demand AS (
      SELECT i.matched_product_id,COALESCE(p.name,i.source_name) name,p.sku,
        SUM(i.quantity) quantity,COUNT(DISTINCT o.vendor) vendor_count,
        GROUP_CONCAT(DISTINCT o.vendor) vendors
      FROM order_import_items i
      JOIN order_imports o ON o.id=i.import_id
      LEFT JOIN products p ON p.id=i.matched_product_id
      WHERE o.status!='COMMITTED'
      GROUP BY CASE WHEN i.matched_product_id IS NULL THEN 'u:'||i.source_name ELSE 'p:'||i.matched_product_id END
    )
    SELECT d.*,COALESCE(k.quantity,0) picking_stock,COALESCE(f.quantity,0) factory_stock,
      MAX(d.quantity-COALESCE(k.quantity,0),0) packing_shortage,
      MIN(MAX(d.quantity-COALESCE(k.quantity,0),0),COALESCE(f.quantity,0)) factory_transfer_needed,
      MAX(d.quantity-COALESCE(k.quantity,0)-COALESCE(f.quantity,0),0) total_shortage,
      CASE
        WHEN d.matched_product_id IS NULL THEN 'UNMATCHED'
        WHEN COALESCE(k.quantity,0)>=d.quantity THEN 'READY'
        WHEN COALESCE(k.quantity,0)+COALESCE(f.quantity,0)>=d.quantity THEN 'NEEDS_PACKING'
        ELSE 'SHORTAGE'
      END stock_status
    FROM demand d
    LEFT JOIN inventory k ON k.product_id=d.matched_product_id AND k.location='PICKING'
    LEFT JOIN inventory f ON f.product_id=d.matched_product_id AND f.location='FACTORY'
    ORDER BY d.name
  `).all();
  res.json({imports,items,summary});
});
app.patch('/api/order-import-items/:id',(req,res,next)=>{try{const data=z.object({productId:z.number().int().positive(),quantity:z.number().int().positive()}).parse(req.body);const exists=db.prepare('SELECT id FROM products WHERE id=? AND active=1').get(data.productId);if(!exists)throw new Error('선택한 상품을 찾을 수 없습니다.');db.prepare('UPDATE order_import_items SET matched_product_id=?,quantity=?,confidence=1 WHERE id=?').run(data.productId,data.quantity,req.params.id);const row=db.prepare('SELECT import_id FROM order_import_items WHERE id=?').get(req.params.id) as {import_id:number}|undefined;if(row){const unmatched=(db.prepare('SELECT COUNT(*) count FROM order_import_items WHERE import_id=? AND matched_product_id IS NULL').get(row.import_id) as {count:number}).count;db.prepare('UPDATE order_imports SET status=? WHERE id=?').run(unmatched?'REVIEW':'READY',row.import_id)}res.json({ok:true})}catch(error){next(error)}});
app.delete('/api/order-imports/:id',(req,res,next)=>{try{const row=db.prepare('SELECT status FROM order_imports WHERE id=?').get(req.params.id) as {status:string}|undefined;if(!row)throw new Error('주문서를 찾을 수 없습니다.');if(row.status==='COMMITTED')throw new Error('이미 출고된 주문서는 삭제할 수 없습니다.');db.prepare('DELETE FROM order_imports WHERE id=?').run(req.params.id);res.json({ok:true})}catch(error){next(error)}});
app.post('/api/order-imports/commit',(req,res,next)=>{try{const data=z.object({importIds:z.array(z.number().int().positive()).min(1)}).parse(req.body);const placeholders=data.importIds.map(()=>'?').join(',');const rows=db.prepare(`SELECT i.*,o.vendor,o.filename FROM order_import_items i JOIN order_imports o ON o.id=i.import_id WHERE o.id IN (${placeholders}) AND o.status!='COMMITTED'`).all(...data.importIds) as Array<{matched_product_id:number|null;quantity:number;vendor:string;filename:string}>;if(!rows.length)throw new Error('출고할 주문서가 없습니다.');if(rows.some(row=>!row.matched_product_id))throw new Error('매칭되지 않은 품목을 먼저 확인해 주세요.');const totals=new Map<number,number>();for(const row of rows)totals.set(row.matched_product_id!, (totals.get(row.matched_product_id!)||0)+row.quantity);db.transaction(()=>{for(const [productId,quantity] of totals){const stock=db.prepare("SELECT quantity FROM inventory WHERE product_id=? AND location='PICKING'").get(productId) as {quantity:number}|undefined;if(!stock||stock.quantity<quantity)throw new Error(`패킹 재고가 부족한 상품이 있습니다. 필요 ${quantity}개 / 보유 ${stock?.quantity||0}개`)}for(const [productId,quantity] of totals){db.prepare("UPDATE inventory SET quantity=quantity-? WHERE product_id=? AND location='PICKING'").run(quantity,productId);db.prepare("INSERT INTO movements(product_id,type,from_location,to_location,quantity,worker_id,memo) VALUES(?,'PICKING_OUT','PICKING',NULL,?,NULL,?)").run(productId,quantity,'거래처 주문서 통합 출고')}db.prepare(`UPDATE order_imports SET status='COMMITTED' WHERE id IN (${placeholders})`).run(...data.importIds)})();res.json({ok:true,products:totals.size,quantity:[...totals.values()].reduce((a,b)=>a+b,0)})}catch(error){next(error)}});
app.post('/api/chat',(req,res,next)=>{try{const message=z.object({message:z.string().trim().min(1)}).parse(req.body).message;let answer='';if(/주문|오더|출고/.test(message)&&/합계|전체|얼마|몇/.test(message)){const row=db.prepare(`SELECT COUNT(DISTINCT o.id) files,COUNT(DISTINCT o.vendor) vendors,COALESCE(SUM(i.quantity),0) quantity FROM order_imports o LEFT JOIN order_import_items i ON i.import_id=o.id WHERE o.status!='COMMITTED'`).get() as {files:number;vendors:number;quantity:number};answer=`현재 출고 대기 주문서는 ${row.files}개 파일, ${row.vendors}개 거래처, 총 ${row.quantity}개입니다.`}else if(/재고/.test(message)){const keyword=message.replace(/재고|알려줘|확인|몇개|몇 개/g,'').trim();const rows=db.prepare(`SELECT p.name,COALESCE(f.quantity,0)+COALESCE(k.quantity,0) total,COALESCE(k.quantity,0) packing FROM products p LEFT JOIN inventory f ON f.product_id=p.id AND f.location='FACTORY' LEFT JOIN inventory k ON k.product_id=p.id AND k.location='PICKING' WHERE p.active=1 AND p.name LIKE ? LIMIT 10`).all(`%${keyword}%`) as Array<{name:string;total:number;packing:number}>;answer=rows.length?rows.map(row=>`${row.name}: 전체 ${row.total}개, 패킹 ${row.packing}개`).join('\n'):'해당 상품을 찾지 못했습니다.'}else answer='상품 재고 또는 출고 대기 주문 합계를 물어보세요. 예: 오늘 주문 합계 알려줘';res.json({answer})}catch(error){next(error)}});
app.get('/api/labels/:id/download', (req,res) => { const row=db.prepare('SELECT source_path,product_name FROM label_templates WHERE id=?').get(req.params.id) as {source_path:string,product_name:string}|undefined; if(!row) return res.status(404).json({message:'라벨을 찾을 수 없습니다.'}); if(!row.source_path.startsWith('C:\\Users\\USER\\Desktop\\유니라벨\\')) return res.status(403).json({message:'허용되지 않은 파일입니다.'}); res.download(row.source_path, `${row.product_name}.uldx`); });
app.post('/api/labels/batch-open', (req,res,next) => { try { const data=z.object({items:z.array(z.object({id:z.number().int().positive(),quantity:z.number().int().min(1).max(100)})).min(1).max(500)}).parse(req.body); const find=db.prepare('SELECT source_path,product_name FROM label_templates WHERE id=?'); let opened=0; console.log('[labels/batch-open] request', {items:data.items.length}); for(const item of data.items){const row=find.get(item.id) as {source_path:string,product_name:string}|undefined;if(!row)throw new Error(`라벨 번호 ${item.id}을 찾을 수 없습니다.`);if(!row.source_path.startsWith('C:\\Users\\USER\\Desktop\\유니라벨\\'))throw new Error('허용되지 않은 라벨 파일입니다.');const safePath=row.source_path.replaceAll("'","''");const command=`Start-Process -FilePath '${safePath}'`;const encoded=Buffer.from(command,'utf16le').toString('base64');const result=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-EncodedCommand',encoded],{windowsHide:true,encoding:'utf8'});if(result.error||result.status!==0){console.error('[labels/batch-open] failed',{id:item.id,product:row.product_name,status:result.status,error:String(result.error||result.stderr)});throw new Error(`${row.product_name} 유니라벨 파일을 열지 못했습니다.`);}opened++;}console.log('[labels/batch-open] success',{opened});res.json({opened});} catch(e){next(e)} });
  app.post('/api/movements', (req,res,next) => { try { const d=z.object({productId:z.number().int().positive(),type:z.enum(['FACTORY_IN','FACTORY_OUT','PICKING_IN','PICKING_OUT','PICKING_RETURN']),quantity:z.number().int().positive(),memo:z.string().default(''),workerId:z.number().int().positive().nullable().default(null)}).parse(req.body); const route=movementMap[d.type]; const id=db.transaction(()=>{ if(route.from){const stock=db.prepare('SELECT quantity FROM inventory WHERE product_id=? AND location=?').get(d.productId,route.from) as {quantity:number}|undefined; if(!stock||stock.quantity<d.quantity) throw new Error(`${route.from==='FACTORY'?'공장':'패킹'} 재고가 부족합니다.`); db.prepare('UPDATE inventory SET quantity=quantity-? WHERE product_id=? AND location=?').run(d.quantity,d.productId,route.from);} if(route.to) db.prepare('UPDATE inventory SET quantity=quantity+? WHERE product_id=? AND location=?').run(d.quantity,d.productId,route.to); return db.prepare('INSERT INTO movements(product_id,type,from_location,to_location,quantity,worker_id,memo) VALUES(?,?,?,?,?,?,?)').run(d.productId,d.type,route.from,route.to,d.quantity,d.workerId,d.memo).lastInsertRowid; })(); res.status(201).json({id:Number(id),...d}); } catch(e){next(e)} });
app.use((err:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{const message=err instanceof Error?err.message:'요청 처리 중 오류가 발생했습니다.'; res.status(message.includes('UNIQUE')?409:400).json({message});});
app.listen(Number(process.env.PORT)||4000,()=>console.log('API: http://localhost:4000/api'));
