import {useEffect,useMemo,useState} from 'react';

type Product={id:number;sku:string;name:string;color:string;factoryStock:number;pickingStock:number};
type Vendor={id:number;name:string;factory_address:string;delivery_address:string};
type Order={id:number;status:string;vendor_name:string;product_name:string;color:string;sku:string;quantity:number;factory_address:string;delivery_address:string;memo:string;ordered_at:string};
type PackingSummary={name:string|null;quantity:number;picking_stock:number;factory_stock:number;stock_status:'READY'|'NEEDS_PACKING'|'SHORTAGE'|'UNMATCHED'};

export function FactoryOrderForm({products,onCreated}:{products:Product[];onCreated?:()=>void}){
 const [vendors,setVendors]=useState<Vendor[]>([]);const [vendorId,setVendorId]=useState(0);const [productId,setProductId]=useState(0);const [quantity,setQuantity]=useState(1);const [factoryAddress,setFactoryAddress]=useState('');const [deliveryAddress,setDeliveryAddress]=useState('');const [memo,setMemo]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/vendors?type=FACTORY').then(r=>r.json()).then(setVendors)},[]);
 const selected=useMemo(()=>vendors.find(v=>v.id===vendorId),[vendors,vendorId]);
 const selectVendor=(id:number)=>{setVendorId(id);const vendor=vendors.find(v=>v.id===id);setFactoryAddress(vendor?.factory_address||'');setDeliveryAddress(vendor?.delivery_address||'')};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const response=await fetch('/api/factory-orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vendorId,productId,quantity,factoryAddress,deliveryAddress,memo})});const data=await response.json();setMessage(response.ok?'공장 발주를 신청했습니다. 대시보드에서 확인할 수 있습니다.':data.message);if(response.ok){setProductId(0);setQuantity(1);setMemo('');onCreated?.()}};
 return <div className="panel factory-order-form"><h2>공장 발주 신청</h2><p>상품과 거래처를 선택하고 공장 주소와 실제 납품 주소를 각각 확인하세요.</p><form onSubmit={submit}><label>거래처<select value={vendorId} onChange={e=>selectVendor(Number(e.target.value))} required><option value="">거래처 선택</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>발주 상품<select value={productId} onChange={e=>setProductId(Number(e.target.value))} required><option value="">상품 선택</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} {p.color} · {p.sku}</option>)}</select></label><label>수량<input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>공장 주소<input value={factoryAddress} onChange={e=>setFactoryAddress(e.target.value)} placeholder="생산 공장 주소" required/></label><label>납품 주소<input value={deliveryAddress} onChange={e=>setDeliveryAddress(e.target.value)} placeholder="완성품을 받을 주소" required/></label><label>메모<input value={memo} onChange={e=>setMemo(e.target.value)} placeholder="납기일, 요청사항 등"/></label><button className="primary" disabled={!selected}>발주 신청</button></form>{!vendors.length&&<div className="notice">거래처 관리에서 거래처와 주소를 먼저 등록해 주세요.</div>}{message&&<div className="notice">{message}</div>}</div>
}

export function DashboardOperations({reloadInventory,onNavigate}:{reloadInventory:()=>void;onNavigate:(page:string)=>void}){
 const [orders,setOrders]=useState<Order[]>([]);const [packing,setPacking]=useState<PackingSummary[]>([]);const [message,setMessage]=useState('');
 const load=()=>{fetch('/api/factory-orders?status=ORDERED').then(r=>r.json()).then(setOrders);fetch('/api/order-imports').then(r=>r.json()).then(data=>setPacking(data.summary||[]))};
 useEffect(()=>{void load()},[]);
 const receive=async(order:Order)=>{if(!window.confirm(`${order.product_name} ${order.quantity}개를 창고 입고 완료할까요?`))return;const response=await fetch(`/api/factory-orders/${order.id}/receive`,{method:'POST'});const data=await response.json();setMessage(response.ok?'창고 입고와 출고이력에 자동 반영했습니다.':data.message);if(response.ok){load();reloadInventory()}};
 const counts={ready:packing.filter(x=>x.stock_status==='READY').length,packing:packing.filter(x=>x.stock_status==='NEEDS_PACKING').length,shortage:packing.filter(x=>x.stock_status==='SHORTAGE').length,unmatched:packing.filter(x=>x.stock_status==='UNMATCHED').length};
 return <div className="dashboard-operations"><div className="panel"><div className="operation-title"><div><h2>공장 발주 품목</h2><p>입고 완료를 누르면 공장재고가 자동으로 증가합니다.</p></div><b>{orders.length}건 대기</b></div>{message&&<div className="notice">{message}</div>}{!orders.length?<div className="empty-queue">입고 대기 중인 공장 발주가 없습니다.</div>:<div className="table"><table><thead><tr><th>거래처</th><th>상품</th><th>수량</th><th>공장 주소</th><th>납품 주소</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.vendor_name}</td><td><b>{o.product_name}</b><small>{o.color} · {o.sku}</small></td><td><b>{o.quantity}</b></td><td>{o.factory_address}</td><td>{o.delivery_address}</td><td><button className="primary compact" onClick={()=>void receive(o)}>입고 완료</button></td></tr>)}</tbody></table></div>}</div><div className="panel packing-check"><div className="operation-title"><div><h2>패킹 출고 확인</h2><p>여러 거래처 주문을 합산한 현재 준비 상태입니다.</p></div><button className="primary compact" onClick={()=>onNavigate('패킹 출고')}>출고 화면 열기</button></div><div className="packing-status-cards"><span className="ok">출고 가능 <b>{counts.ready}</b></span><span className="warn">패킹 필요 <b>{counts.packing}</b></span><span className="bad">재고 부족 <b>{counts.shortage}</b></span><span>매칭 필요 <b>{counts.unmatched}</b></span></div>{packing.length>0&&<div className="table compact-table"><table><thead><tr><th>상품</th><th>주문</th><th>패킹</th><th>공장</th><th>상태</th></tr></thead><tbody>{packing.slice(0,8).map((row,index)=><tr key={`${row.name}-${index}`}><td>{row.name||'상품 매칭 필요'}</td><td>{row.quantity}</td><td>{row.picking_stock}</td><td>{row.factory_stock}</td><td>{row.stock_status==='READY'?'출고 가능':row.stock_status==='NEEDS_PACKING'?'패킹 입고 필요':row.stock_status==='SHORTAGE'?'재고 부족':'상품 매칭 필요'}</td></tr>)}</tbody></table></div>}</div></div>
}
