import { useMemo, useState } from 'react';

type Product={id:number;name:string;catalog_name?:string;image_path?:string;factoryStock:number;pickingStock:number;totalStock:number};
type Row={name:string;factory:number;picking:number;total:number;small:number;large:number;products:Product[]};
type Section={title:string;rows:Row[]};

const K={basic:'\uAE30\uBCF8\uBC31',small:'\uC2A4\uBAB0',large:'\uB77C\uC9C0',long:'\uB871',mini:'\uBBF8\uB2C8\uBC31',heart:'\uD558\uD2B8\uBC31',pier:'\uD53C\uC5B4\uBC31',lagoon:'\uB77C\uAD70 \uBE45 \uBC31',accordion:'\uC544\uCF54\uB514\uC5B8\uBC31',quilt:'\uD03C\uD305 \uD30C\uC6B0\uCE58',squareA:'\uC2A4\uD018\uC5B4 \uD30C\uC6B0\uCE58 A',squareB:'\uC2A4\uD018\uC5B4 \uD30C\uC6B0\uCE58 B',square3:'\uC2A4\uD018\uC5B4 3\uD30C\uC6B0\uCE58 \uBC31',memory:'\uBA54\uBAA8\uB9AC\uBC31',brick:'\uBE0C\uB9AD\uBC31',other:'\uAE30\uD0C0 \uAC00\uBC29\xB7\uC18C\uD488',pouch:'\uD30C\uC6B0\uCE58'};
const order=[K.basic,K.mini,K.heart,K.quilt,K.squareA,K.squareB,K.square3,K.pier,K.lagoon,K.accordion,K.brick,K.memory,K.other];
const miniOrder=['남해','디스코바이올렛','디스코브론즈','디스코스카이','디스코핑크','라일락','리치','릴리','머드','모카','바비','바함사','블로썸','솔져','애플','에그','여수','장미','잭슨','초코','춘장','카멜','캔디','타임','피스타','피오니','하마','호일'];
const heartOrder=['골드','브라운','네이비','와인','블랙','실버','아이보리','피치','민트그레이'];
const pierOrder=['블랙','골드','브라운','실버','아이보리','와인','핑크'];
const quiltOrder=['민트그레이','블랙','실버','카멜','핑크'];
const squareAOrder=['디스코 골드','남해','디스코 바이올렛','디스코 브론즈','솔져','디스코 스카이','여수','장미','초코','춘장','카멜','디스코 핑크','호일'];
const squareBOrder=['라일락','유니콘','블루베리','체리','릴리','피스타','애플','레몬'];
const square3Order=['도트 민트','도트 핑크','ST 블루','ST 핑크','레오파트 핑크','레오파트 그린','트위드 핑크','트위드 블랙'];
const lagoonOrder=['블랙','아이보리','카멜','카키'];
const accordionOrder=['블랙','실버','아이보리','핑크','민트그레이'];
const brickOrder=['캔디','블루베리','릴리','춘장','카멜','타임','레몬','브론즈'];
const memoryOrder=['남해','리치','에그','춘장','카멜','캔디','호일'];
const otherGroupOrder=['미니 파우치','멍미참','꽃참','하트참','타월참','럭키참','미니참','롱참','로프참','로프 스트랩','핸드폰 스트랩','솔참','털실폼폼','만두백','밍크백','어그백','호피백'];
const ropeStrapOrder=['그레이','블루','블랙','스카이','오렌지','올리브','와인','카멜'];

function sectionOf(value:string){const name=value.toLowerCase().replace(/\s/g,'');if(name.includes(K.basic))return K.basic;if(name.includes('\uBBF8\uB2C8\uBC31'))return K.mini;if(name.includes(K.heart))return K.heart;if(name.includes('\uD53C\uC5B4\uBC31'))return K.pier;if(name.includes('\uB77C\uAD70')&&name.includes('\uBE45'))return K.lagoon;if(name.includes('\uC544\uCF54\uB514\uC5B8'))return K.accordion;if((name.includes('\uD03C\uD305')||name.includes('\uD004\uD305')||name.includes('\uD018\uD305'))&&name.includes(K.pouch))return K.quilt;if(name.includes('\uC2A4\uD018\uC5B4')&&name.includes('\uD30C\uC6B0\uCE58a'))return K.squareA;if(name.includes('\uC2A4\uD018\uC5B4')&&name.includes('\uD30C\uC6B0\uCE58b'))return K.squareB;if(name.includes('\uC2A4\uD018\uC5B43')&&name.includes(K.pouch))return K.square3;if(name.includes('\uBA54\uBAA8\uB9AC'))return K.memory;if(name.includes('\uBE0C\uB9AD'))return K.brick;return K.other}
function basicSize(value:string){const name=value.toLowerCase().replace(/\s/g,'');if(/s$/.test(name)||name.endsWith(K.small))return 'S';if(/l$/.test(name)||name.endsWith(K.large)||name.endsWith(K.long))return 'L';return ''}
function basicLabel(value:string){return value.replaceAll(K.basic,'').replace(/\s+(S|L)$/i,'').replace(new RegExp(`\\s+(${K.small}|${K.large}|${K.long})$`),'').replace(/\s+/g,' ').trim()}
function compact(value:string){return value.replace(/\s/g,'').toLowerCase()}
function miniLabel(value:string){const cleaned=value.replaceAll(K.mini,'').trim();const aliases:Record<string,string>={'바람과함께사라지다':'바함사','피스타치오':'피스타'};return aliases[compact(cleaned)]||miniOrder.find(name=>compact(name)===compact(cleaned))||''}
function heartLabel(value:string){const cleaned=value.replaceAll(K.heart,'').trim();if(compact(cleaned)==='호일')return '실버';return heartOrder.find(name=>compact(name)===compact(cleaned))||''}
function pierLabel(value:string){const cleaned=value.replaceAll(K.pier,'').replace(/미니|라지|스몰/gi,'').replace(/\s+(S|L)$/i,'').replace(/\s+/g,' ').trim();return pierOrder.find(name=>compact(name)===compact(cleaned))||''}
function pierSize(value:string){const name=compact(value);if(name.includes('피어백미니')||name.endsWith('s'))return 'S';if(name.includes('피어백')||name.endsWith('l'))return 'L';return ''}
function quiltLabel(value:string){const cleaned=value.replace(/(퀼팅|퀄팅|퀘팅)\s*파우치/g,'').trim();return quiltOrder.find(name=>compact(name)===compact(cleaned))||''}
function fixedLabel(value:string,names:string[],pattern:RegExp){const cleaned=value.replace(pattern,'').replaceAll('체리쥬빌레','체리').replaceAll('피스타치오','피스타').replaceAll('레오파드','레오파트').trim();return names.find(name=>compact(name)===compact(cleaned))||''}
function sizeRank(product:Product){const size=basicSize(product.name)||pierSize(product.name);return size==='S'?0:size==='L'?1:2}
function stockNumber(value:unknown){const number=Number(value);return Number.isFinite(number)?number:0}
function matchedFixedLabel(section:string,catalogLabel:string,productName:string){const resolve=(value:string)=>section===K.mini?miniLabel(value):section===K.heart?heartLabel(value):section===K.pier?pierLabel(value):section===K.quilt?quiltLabel(value):section===K.squareA?fixedLabel(value,squareAOrder,/스퀘어\s*파우치\s*A/gi):section===K.squareB?fixedLabel(value,squareBOrder,/스퀘어\s*파우치\s*B/gi):section===K.square3?fixedLabel(value,square3Order,/스퀘어\s*3\s*파우치\s*백?/gi):section===K.lagoon?fixedLabel(value,lagoonOrder,/라군\s*빅\s*백/gi):section===K.accordion?fixedLabel(value,accordionOrder,/아코디언\s*백?/gi):section===K.brick?fixedLabel(value,brickOrder,/브릭\s*백?/gi):section===K.memory?fixedLabel(value,memoryOrder,/메모리\s*백?/gi):value;return resolve(catalogLabel)||resolve(productName)}
function otherGroupOf(value:string){const name=compact(value);if(name.includes('미니파우치'))return '미니 파우치';if(name.includes('타월참'))return '타월참';if(name.includes('멍미'))return '멍미참';if(name.includes('꽃'))return '꽃참';if(name.includes('하트참'))return '하트참';if(name.includes('미니구슬')||name.includes('미니참'))return '미니참';if(name.includes('롱구슬')||name.includes('롱참')||/^구슬\d+$/.test(name))return '롱참';if(name.includes('솔참'))return '솔참';if(name.includes('털실'))return '털실폼폼';if(name.includes('로프스트랩')||name.includes('로프스트립'))return '로프 스트랩';if(name.includes('h·p스트랩')||name.includes('hp스트랩')||name.includes('핸드폰스트랩')||name.includes('핸드폰스트립')||name.includes('핸드폰줄'))return '핸드폰 스트랩';if(name.includes('로프참')||/^로프\d+$/.test(name))return '로프참';if(name.includes('만두백'))return '만두백';if(name.includes('밍크백'))return '밍크백';if(name.includes('어그백'))return '어그백';if(name.includes('호피백'))return '호피백';return '럭키참'}

export default function InventoryDashboard({items}:{items:Product[]}){
 const [selected,setSelected]=useState<Row|null>(null);
 const sections=useMemo(()=>{const maps=new Map<string,Map<string,Row>>();const empty=(name:string):Row=>({name,factory:0,picking:0,total:0,small:0,large:0,products:[]});const templates:Array<[string,string[]]>=[[K.mini,miniOrder],[K.heart,heartOrder],[K.pier,pierOrder],[K.quilt,quiltOrder],[K.squareA,squareAOrder],[K.squareB,squareBOrder],[K.square3,square3Order],[K.lagoon,lagoonOrder],[K.accordion,accordionOrder],[K.brick,brickOrder],[K.memory,memoryOrder]];templates.forEach(([title,names])=>maps.set(title,new Map(names.map(name=>[name,empty(name)]))));const fixedSections=templates.map(([title])=>title);for(const product of items){const section=sectionOf(product.name);const sourceLabel=product.catalog_name||product.name;const label=section===K.basic?basicLabel(sourceLabel):section===K.other?product.name:matchedFixedLabel(section,sourceLabel,product.name);if(fixedSections.includes(section)&&!label)continue;if(!maps.has(section))maps.set(section,new Map());const map=maps.get(section)!;const row=map.get(label)||empty(label);const factory=stockNumber(product.factoryStock);const picking=stockNumber(product.pickingStock);const stock=factory+picking;row.factory+=factory;row.picking+=picking;row.total+=stock;if(section===K.basic||section===K.pier){const size=section===K.basic?basicSize(product.name):pierSize(product.name);if(size==='S')row.small+=stock;if(size==='L')row.large+=stock}row.products.push(product);map.set(label,row)}return order.map(title=>{const rows=[...(maps.get(title)?.values()||[])];return{title,rows:fixedSections.includes(title)?rows:rows.sort((a,b)=>a.name.localeCompare(b.name,'ko-KR',{numeric:true}))}}).filter(section=>section.rows.length) as Section[]},[items]);
 const findSection=(title:string)=>sections.find(section=>section.title===title);const basicSection=findSection(K.basic);const basicSplitIndex=basicSection?.rows.findIndex(row=>compact(row.name)===compact('펌킨'))??-1;const basicFirst=basicSection?.rows.slice(0,basicSplitIndex>=0?basicSplitIndex+1:Math.ceil((basicSection?.rows.length||0)/2))||[];const basicRest=basicSection?.rows.slice(basicFirst.length)||[];const other=findSection(K.other);const otherGroups=otherGroupOrder.map(title=>({title,rows:(other?.rows||[]).filter(row=>otherGroupOf(row.name)===title)})).filter(group=>group.rows.length);
 const renderBasicRows=(rows:Row[])=><tbody>{rows.map(row=><tr key={row.name} onClick={()=>setSelected(row)}><td>{row.name}</td><td>{row.small.toLocaleString()}</td><td>{row.large.toLocaleString()}</td></tr>)}</tbody>;
 const renderBasicColumn=(rows:Row[],key:string)=><section className="inventory-section basic-section" key={key}><table><thead><tr><th>{K.basic}</th><th>S</th><th>L</th></tr></thead>{renderBasicRows(rows)}</table></section>;
 const sizeBagRows=(section:Section)=>{const rows=new Map<string,Row>();for(const source of section.rows){const label=source.name.replace(section.title,'').replace(/\s*(미니|라지)\s*$/,'').trim();const row=rows.get(label)||{name:label,factory:0,picking:0,total:0,small:0,large:0,products:[]};row.factory+=source.factory;row.picking+=source.picking;row.total+=source.total;if(source.name.includes('미니'))row.small+=source.total;if(source.name.includes('라지'))row.large+=source.total;row.products.push(...source.products);rows.set(label,row)}return [...rows.values()].sort((a,b)=>a.name.localeCompare(b.name,'ko-KR'))};
 const renderSection=(section:Section)=>{
  if(section.title===K.basic){const size=Math.ceil(section.rows.length/2);const groups=Array.from({length:2},(_,index)=>section.rows.slice(index*size,(index+1)*size)).filter(rows=>rows.length);return <section className="inventory-section basic-section" key={section.title}><div className="basic-double">{groups.map((rows,index)=><table key={index}><thead><tr><th>{K.basic}</th><th>S</th><th>L</th></tr></thead>{renderBasicRows(rows)}</table>)}</div></section>}
  if(section.title===K.pier)return <section className="inventory-section pier-section" key={section.title}><table><thead><tr><th>{K.pier}</th><th>S</th><th>L</th></tr></thead>{renderBasicRows(section.rows)}</table></section>
  if(section.title==='밍크백'||section.title==='어그백')return <section className="inventory-section basic-section" key={section.title}><table><thead><tr><th>{section.title}</th><th>S</th><th>L</th></tr></thead>{renderBasicRows(sizeBagRows(section))}</table></section>
  if(section.title==='로프 스트랩'){const rows=ropeStrapOrder.map(color=>section.rows.find(row=>compact(row.name).endsWith(compact(color)))).filter((row):row is Row=>Boolean(row)).map(row=>({...row,name:row.name.replace('로프 스트랩','').trim()}));return <section className="inventory-section" key={section.title}><h3>{section.title}</h3><table><tbody>{rows.map(row=><tr key={row.name} onClick={()=>setSelected(row)}><td>{row.name}</td><td>{row.total.toLocaleString()}</td></tr>)}</tbody></table></section>}
  if(section.title==='호피백'){const rows=section.rows.map(row=>({...row,name:row.name.replace('호피백','').replace('미니','').trim()}));return <section className="inventory-section" key={section.title}><h3>{section.title}</h3><table><tbody>{rows.map(row=><tr key={row.name} onClick={()=>setSelected(row)}><td>{row.name}</td><td>{row.total.toLocaleString()}</td></tr>)}</tbody></table></section>}
  return <section className="inventory-section" key={section.title}><h3>{section.title}</h3><table><tbody>{section.rows.map(row=><tr key={row.name} onClick={()=>setSelected(row)}><td>{row.name}</td><td>{row.total.toLocaleString()}</td></tr>)}</tbody></table></section>
 };
 const stack=(titles:string[])=>titles.map(title=>findSection(title)).filter((section):section is Section=>Boolean(section)).map(renderSection);
 return <><div className="inventory-print-page main-inventory-page"><div className="inventory-layout-five"><div className="fixed-column column-one">{renderBasicColumn(basicFirst,'basic-first')}</div><div className="fixed-column column-two">{renderBasicColumn(basicRest,'basic-rest')}{stack([K.mini,K.heart])}</div><div className="fixed-column column-three">{stack([K.quilt,K.squareA,K.squareB,K.square3])}</div><div className="fixed-column column-four">{stack([K.pier,K.lagoon,K.accordion,K.brick,K.memory])}</div></div></div>{other&&<div className="inventory-print-page other-inventory-page"><h2>{K.other}</h2><div className="other-category-grid">{otherGroups.map(renderSection)}</div></div>}{selected&&<div className="photo-overlay" onMouseDown={()=>setSelected(null)}><div className="photo-popup" onMouseDown={event=>event.stopPropagation()}><button className="photo-close" onClick={()=>setSelected(null)}>x</button><h2>{selected.name}</h2><div className="stock-definition"><div><strong>{'\uC804\uCCB4\uC7AC\uACE0'} {selected.total.toLocaleString()}{'\uAC1C'}</strong><span>{'\uACF5\uC7A5\uC7AC\uACE0'} {selected.factory.toLocaleString()} + {'\uD328\uD0B9\uC7AC\uACE0'} {selected.picking.toLocaleString()}</span></div><p><b>{'\uACF5\uC7A5\uC7AC\uACE0'}</b> {'\uD68C\uC0AC\uC5D0 \uB4E4\uC5B4\uC654\uC9C0\uB9CC \uC544\uC9C1 \uD3EC\uC7A5\uB418\uC9C0 \uC54A\uC740 \uC0C1\uD488'}<br/><b>{'\uD328\uD0B9\uC7AC\uACE0'}</b> {'\uD3EC\uC7A5\uC774 \uC644\uB8CC\uB418\uC5B4 \uBC14\uB85C \uCD9C\uACE0\uD560 \uC218 \uC788\uB294 \uC0C1\uD488'}</p></div><div className="photo-grid">{selected.products.filter(product=>product.image_path).sort((a,b)=>sizeRank(a)-sizeRank(b)).map(product=><figure key={product.id}><img src={product.image_path} alt={product.name}/><figcaption>{product.name}</figcaption></figure>)}{!selected.products.some(product=>product.image_path)&&<div className="photo-missing">{'\uB4F1\uB85D\uB41C \uC0AC\uC9C4\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.'}</div>}</div></div></div>}</>;
}
