import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileText, Trash2, Upload } from 'lucide-react';

type Product={id:number;name:string;sku:string;factoryStock:number;pickingStock:number};
type Vendor={id:number;name:string};
type ImportRow={id:number;vendor:string;filename:string;status:string;item_count:number;total_quantity:number;unmatched_count:number};
type Item={id:number;import_id:number;vendor:string;filename:string;source_name:string;quantity:number;matched_product_id:number|null;matched_name:string|null;confidence:number};
type Summary={matched_product_id:number|null;name:string|null;sku:string|null;quantity:number;vendor_count:number;vendors:string;picking_stock:number;factory_stock:number;packing_shortage:number;factory_transfer_needed:number;total_shortage:number;stock_status:'READY'|'NEEDS_PACKING'|'SHORTAGE'|'UNMATCHED'};

export default function PackingOrders({products,reloadInventory}:{products:Product[];reloadInventory:()=>void}){
 const [vendor,setVendor]=useState('');const [vendors,setVendors]=useState<Vendor[]>([]);const [files,setFiles]=useState<File[]>([]);const [imports,setImports]=useState<ImportRow[]>([]);const [items,setItems]=useState<Item[]>([]);const [summary,setSummary]=useState<Summary[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
 const load=()=>fetch('/api/order-imports').then(r=>r.json()).then(data=>{setImports(data.imports);setItems(data.items);setSummary(data.summary)});
 useEffect(()=>{void load();fetch('/api/vendors').then(r=>r.json()).then(setVendors)},[]);const readyIds=useMemo(()=>imports.filter(row=>row.status==='READY').map(row=>row.id),[imports]);const stockReady=summary.length>0&&summary.every(row=>row.stock_status==='READY');
 const upload=async(event:React.FormEvent)=>{event.preventDefault();if(!vendor.trim()||!files.length){setMessage('거래처명과 주문서 파일을 선택해 주세요.');return}setBusy(true);setMessage('문서를 읽고 품목을 매칭하고 있습니다. 이미지 파일은 시간이 조금 걸릴 수 있습니다.');const body=new FormData();body.append('vendor',vendor.trim());files.forEach(file=>body.append('files',file));try{const response=await fetch('/api/order-imports',{method:'POST',body});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessage(`${data.imports.length}개 주문서를 분석했습니다. 확인 필요 품목을 검토해 주세요.`);setFiles([]);if(inputRef.current)inputRef.current.value='';await load()}catch(error){setMessage(error instanceof Error?error.message:'문서 분석에 실패했습니다.')}finally{setBusy(false)}};
 const updateItem=async(item:Item,productId:number)=>{if(!productId)return;const response=await fetch(`/api/order-import-items/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,quantity:item.quantity})});const data=await response.json();setMessage(response.ok?'품목 매칭을 저장했습니다.':data.message);if(response.ok)await load()};
 const remove=async(id:number)=>{const response=await fetch(`/api/order-imports/${id}`,{method:'DELETE'});const data=await response.json();setMessage(response.ok?'주문서를 대기목록에서 제거했습니다.':data.message);if(response.ok)await load()};
 const commit=async()=>{if(!readyIds.length){setMessage('매칭 확인이 끝난 주문서가 없습니다.');return}if(!stockReady){setMessage('패킹 준비가 안 된 품목이 있습니다. 공장 재고를 패킹 입고한 뒤 다시 확인해 주세요.');return}if(!window.confirm(`${readyIds.length}개 주문서를 합산하여 패킹 재고에서 출고할까요?`))return;const response=await fetch('/api/order-imports/commit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({importIds:readyIds})});const data=await response.json();setMessage(response.ok?`${data.quantity}개 통합 출고를 완료했습니다.`:data.message);if(response.ok){await load();reloadInventory()}};
 return <div className="packing-orders"><div className="panel order-upload-panel"><h2>거래처 주문서 통합 업로드</h2><p>거래처를 선택하고 PDF, JPG, PNG, Excel 주문서를 여러 개 올리면 상품과 수량을 합산합니다.</p><form onSubmit={upload}><label>거래처 선택<select value={vendor} onChange={event=>setVendor(event.target.value)}><option value="">거래처를 선택하세요</option>{vendors.map(row=><option key={row.id} value={row.name}>{row.name}</option>)}</select></label><label className="order-file-input"><span>주문서 파일</span><input ref={inputRef} type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.bmp,.xlsx" onChange={event=>setFiles([...event.target.files||[]])}/><small>{files.length?`${files.length}개 파일 선택됨`:'여러 파일을 한 번에 선택할 수 있습니다.'}</small></label><button className="primary" disabled={busy||!vendors.length}><Upload size={18}/>{busy?'문서 분석 중':'주문서 분석하기'}</button></form>{!vendors.length&&<div className="notice">먼저 거래처 관리에서 거래처를 등록해 주세요.</div>}{message&&<div className="notice">{message}</div>}</div>
 <div className="panel"><div className="order-section-title"><div><h2>업체별 주문서</h2><p>상품 매칭과 패킹 준비가 모두 끝난 주문서만 출고할 수 있습니다.</p></div><button className="primary" onClick={commit} disabled={!readyIds.length||!stockReady}><CheckCircle2 size={18}/> 패킹 준비 완료 주문 통합 출고</button></div>{!imports.length?<div className="empty-queue">등록된 주문서가 없습니다.</div>:<div className="table"><table><thead><tr><th>거래처</th><th>파일</th><th>품목</th><th>총수량</th><th>상태</th><th></th></tr></thead><tbody>{imports.map(row=><tr key={row.id}><td>{row.vendor}</td><td><FileText size={15}/> {row.filename}</td><td>{row.item_count}</td><td><b>{row.total_quantity}</b></td><td>{row.status==='READY'?<span className="order-ready"><CheckCircle2 size={15}/>매칭 완료</span>:row.status==='COMMITTED'?<span>출고 완료</span>:<span className="order-review"><AlertTriangle size={15}/>확인 필요 {row.unmatched_count}</span>}</td><td>{row.status!=='COMMITTED'&&<button className="queue-remove" onClick={()=>void remove(row.id)} title="삭제"><Trash2 size={16}/></button>}</td></tr>)}</tbody></table></div>}</div>
 <div className="order-two-columns"><div className="panel"><h2>품목 매칭 확인</h2><p>잘못 읽힌 품목은 실제 MIYANSOL 상품으로 변경하세요.</p><div className="order-match-list">{items.map(item=><div className={item.matched_product_id?'order-match-row':'order-match-row unmatched'} key={item.id}><div><b>{item.source_name}</b><small>{item.vendor} · {item.filename} · 주문 {item.quantity}개</small></div><select value={item.matched_product_id||''} onChange={event=>void updateItem(item,Number(event.target.value))}><option value="">상품 선택 필요</option>{products.map(product=><option value={product.id} key={product.id}>{product.name} · 공장 {product.factoryStock} · 패킹 {product.pickingStock}</option>)}</select></div>)}</div></div><div className="panel stock-compare-panel"><h2>주문·재고·패킹 준비 현황</h2><p>여러 업체 주문을 합산하여 현재 패킹 가능 여부를 표시합니다.</p><div className="table order-summary"><table><thead><tr><th>상품</th><th>주문</th><th>패킹재고</th><th>공장재고</th><th>준비 상태</th></tr></thead><tbody>{summary.map((row,index)=><tr key={`${row.matched_product_id}-${index}`}><td>{row.name||'매칭 필요'}<small>{row.vendors}</small></td><td><b>{row.quantity}</b></td><td>{row.picking_stock}</td><td>{row.factory_stock}</td><td>{row.stock_status==='READY'?<span className="stock-ready">출고 가능</span>:row.stock_status==='NEEDS_PACKING'?<span className="stock-packing">패킹 입고 {row.factory_transfer_needed}개 필요</span>:row.stock_status==='SHORTAGE'?<span className="stock-shortage">전체재고 {row.total_shortage}개 부족</span>:<span className="stock-unmatched">품목 매칭 필요</span>}</td></tr>)}</tbody></table></div></div></div></div>
}
